Algoritmo "cotacao"
// Escreva um algoritmo para calcular e mostrar o valor da conversão
// de uma quantia em dólares para reais. Crie variáveis para guardar
// o valor da cotação do dólar do dia,
// o valor em dólares e o valor do resultado da conversão.

Var
valor_cotacao: real
dolares: real
resultado: real

Inicio

escreva("Cotacao do dia: ")
leia(valor_cotacao)

escreva("Valor em dólares: ")
leia(dolares)

resultado <- dolares * valor_cotacao

escreva(resultado)

Fimalgoritmo